version: "3"
services:
  simu-server:
    build: .
    image: simu-server/server
    environment:
      - SERVER_ADMIN_PW=${SERVER_ADMIN_PW}
    ports:
      - "13353:13353"
    volumes:
      - ./simutrans:/simutrans:Z
  autosave:
    build: ./autosave
    image: simu-server/autosave
    environment:
      - SERVER_ADMIN_PW=${SERVER_ADMIN_PW}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
