version: "3"
services:
  simu:
    image: simu-server:latest
    ports:
      - "13353:13353"
    volumes:
      - ./simutrans/pak:/simutrans/pak:Z
      - ./simutrans/config:/simutrans/config:Z
      - ./simutrans/server13353-network.sve:/simutrans/server13353-network.sve:Z
      - ./simutrans/server13353-pwdhash.sve:/simutrans/server13353-pwdhash.sve:Z
